[env]
TERM                  = "xterm-256color"

[window]
#dimensions            = { columns = 0, lines = 0 }
#position              = { x = 0, y = 0 }
padding               = { x = 2, y = 2 }
dynamic_padding       = true
decorations           = "None"
opacity               = 0.75
blur                  = false
startup_mode          = "Maximized"
title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"

[colors.primary]
background            = "#1E1E2E"
foreground            = "#CDD6F4"
dim_foreground        = "#CDD6F4"
bright_foreground     = "#CDD6F4"

[colors.cursor]
text                  = "#1E1E2E"
cursor                = "#F5E0DC"

[colors.vi_mode_cursor]
text                  = "#1E1E2E"
cursor                = "#B4BEFE"

[colors.search.matches]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.search.focused_match]
foreground            = "#1E1E2E"
background            = "#A6E3A1"

[colors.hints.start]
foreground            = "#1E1E2E"
background            = "#F9E2AF"

[colors.hints.end]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.line_indicator]
#foreground            = "None"
#background            = "None"

[colors.footer_bar]
foreground            = "#1E1E2E"
background            = "#A6ADC8"

[colors.selection]
text                  = "#1E1E2E"
background            = "#F5E0DC"

[colors.normal]
black                 = "#45475A"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#BAC2DE"

[colors.bright]
black                 = "#585B70"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#A6ADC8"

[colors.dim]
black                 = "#45475A"
red                   = "#F38BA8"
green                 = "#A6E3A1"
yellow                = "#F9E2AF"
blue                  = "#89B4FA"
magenta               = "#F5C2E7"
cyan                  = "#94E2D5"
white                 = "#BAC2DE"

[colors]
indexed_colors = [
  { index = 16, color = "#FAB387" },
  { index = 17, color = "#F5E0DC" },
]

